"""Tests for cex_check_v2 — vibecheck's VNNLIB-2.0 counterexample validator.

Two things are pinned here:

1. GOLDEN VERDICTS (approach C): a deterministic corpus of (onnx, spec, ce)
   triples with the accept/reject verdict FROZEN from the VNN-COMP 2026
   competition checker. The frozen values were generated by replaying each case
   through the (now-removed) vendored `vnncomp_cex_v2` checker (single-net via `validate_cex_v2`,
   multi-net via its `validate_vnnlib2_counterexample` network-field list) — see
   `scratch/gen_cex_golden.py`. cex_check_v2 must reproduce every verdict, so a
   `sat` vibecheck emits is accepted by the scorer and vice-versa. This is the
   bit-identical guarantee that lets us drop the vendored competition code.

2. BRANCH COVERAGE: the error dispositions (NO_CE / MALFORMED_CE / UNSUPPORTED)
   and the arithmetic/boolean evaluation paths.
"""
import os
import tempfile

import numpy as np
import onnx
import pytest
from onnx import TensorProto, helper, numpy_helper

from vibecheck.cex_check_v2 import (
    validate_cex_v2, ACCEPTED_RESULTS, CexResult, parse_text_assignment,
)


# --------------------------------------------------------------------------- #
# ONNX + spec + counterexample builders (deterministic).
# --------------------------------------------------------------------------- #
def _save_onnx(model, tmp, name):
    path = os.path.join(tmp, name)
    onnx.save(model, path)
    return path


def _gemm_model(W, b, in_dim, out_dim):
    Wt = numpy_helper.from_array(np.asarray(W, np.float32), name='W')
    bt = numpy_helper.from_array(np.asarray(b, np.float32), name='b')
    inp = helper.make_tensor_value_info('X', TensorProto.FLOAT, [1, in_dim])
    out = helper.make_tensor_value_info('Y', TensorProto.FLOAT, [1, out_dim])
    node = helper.make_node('Gemm', ['X', 'W', 'b'], ['Y'], transB=1)
    graph = helper.make_graph([node], 'm', [inp], [out], initializer=[Wt, bt])
    model = helper.make_model(graph, opset_imports=[helper.make_opsetid('', 13)])
    model.ir_version = 7
    return model


def first_coord_net(tmp, name='first.onnx'):
    """Y[1,1] = X[0,0]  (W = [[1,0]])."""
    return _save_onnx(_gemm_model([[1.0, 0.0]], [0.0], 2, 1), tmp, name)


def scaled_id_net(tmp, scale, name):
    """Y[1,2] = scale * X[1,2]."""
    W = (scale * np.eye(2)).tolist()
    return _save_onnx(_gemm_model(W, [0.0, 0.0], 2, 2), tmp, name)


def _write(tmp, name, text):
    path = os.path.join(tmp, name)
    with open(path, 'w') as f:
        f.write(text)
    return path


def single_spec(tmp, out_assert, lo=(0.0, 0.0), hi=(1.0, 1.0), name='s.vnnlib'):
    text = ("(vnnlib-version <2.0>)\n"
            "(declare-network f (declare-input X real [1,2]) (declare-output Y real [1,1]))\n"
            f"(assert (>= X[0,0] {lo[0]}))\n(assert (<= X[0,0] {hi[0]}))\n"
            f"(assert (>= X[0,1] {lo[1]}))\n(assert (<= X[0,1] {hi[1]}))\n"
            f"(assert {out_assert})\n")
    return _write(tmp, name, text)


def single_ce(tmp, x0, x1, y, name='c.ce'):
    return _write(tmp, name, f"X real [1,2]\n{x0!r}\n{x1!r}\nY real [1,1]\n{y!r}\n")


def pair_spec(tmp, link, out_assert, name='p.vnnlib'):
    text = ("(vnnlib-version <2.0>)\n"
            "(declare-network f (declare-input X_f real [1,2]) (declare-output Y_f real [1,2]))\n"
            f"(declare-network g {link} (declare-input X_g real [1,2]) (declare-output Y_g real [1,2]))\n"
            "(assert (>= X_f[0,0] 0.0))(assert (<= X_f[0,0] 1.0))(assert (>= X_f[0,1] 0.0))(assert (<= X_f[0,1] 1.0))\n"
            "(assert (>= X_g[0,0] 0.0))(assert (<= X_g[0,0] 1.0))(assert (>= X_g[0,1] 0.0))(assert (<= X_g[0,1] 1.0))\n"
            f"(assert {out_assert})\n")
    return _write(tmp, name, text)


def pair_nets(tmp, link, scale):
    """Build (path_f, path_g) as vibecheck's resolve_pair_paths would: an
    `equal-to` g IS f, so it reuses f's ONE onnx path; an isomorphic g is a
    distinct net with its own path."""
    pf = scaled_id_net(tmp, 1.0, 'f.onnx')
    pg = pf if link == '(equal-to f)' else scaled_id_net(tmp, scale, 'g.onnx')
    return pf, pg


def pair_ce(tmp, xf, yf, xg, yg, name='p.ce'):
    return _write(tmp, name,
                  f"X_f real [1,2]\n{xf[0]!r}\n{xf[1]!r}\nY_f real [1,2]\n{yf[0]!r}\n{yf[1]!r}\n"
                  f"X_g real [1,2]\n{xg[0]!r}\n{xg[1]!r}\nY_g real [1,2]\n{yg[0]!r}\n{yg[1]!r}\n")


# --------------------------------------------------------------------------- #
# 1. Golden verdicts — single network.
# --------------------------------------------------------------------------- #
# (out_assert, x0, x1, expected result)  — Y = X[0,0].
_SINGLE_GOLDEN = [
    ('gt_clear',      '(> Y[0,0] 0.5)',  0.9,   0.3, CexResult.CORRECT),
    ('gt_boundary',   '(> Y[0,0] 0.5)',  0.5,   0.3, CexResult.SPEC_NOT_VIOLATED),
    ('gt_below',      '(> Y[0,0] 0.5)',  0.4,   0.3, CexResult.SPEC_NOT_VIOLATED),
    ('lt_clear',      '(< Y[0,0] 0.5)',  0.1,   0.3, CexResult.CORRECT),
    ('lt_boundary',   '(< Y[0,0] 0.5)',  0.5,   0.3, CexResult.SPEC_NOT_VIOLATED),
    ('ge_boundary',   '(>= Y[0,0] 0.5)', 0.5,   0.3, CexResult.CORRECT),
    ('le_boundary',   '(<= Y[0,0] 0.5)', 0.5,   0.3, CexResult.CORRECT),
    ('in_tol_low',    '(< Y[0,0] 0.5)', -5e-5,  0.3, CexResult.CORRECT_UP_TO_TOLERANCE),
    ('in_tol_high',   '(> Y[0,0] 0.5)',  1.00005, 0.3, CexResult.CORRECT_UP_TO_TOLERANCE),
    ('far_outside',   '(> Y[0,0] 0.5)',  1.5,   0.3, CexResult.SPEC_NOT_VIOLATED),
    ('below_tol',     '(< Y[0,0] 0.5)', -1e-3,  0.3, CexResult.SPEC_NOT_VIOLATED),
]


@pytest.mark.parametrize('name,out,x0,x1,expected', _SINGLE_GOLDEN,
                         ids=[c[0] for c in _SINGLE_GOLDEN])
def test_single_golden(tmp_path, name, out, x0, x1, expected):
    tmp = str(tmp_path)
    onnx_p = first_coord_net(tmp)
    spec_p = single_spec(tmp, out)
    ce_p = single_ce(tmp, x0, x1, float(x0))
    result, _ = validate_cex_v2(onnx_p, spec_p, ce_p)
    assert result == expected
    assert (result in ACCEPTED_RESULTS) == (
        expected in (CexResult.CORRECT, CexResult.CORRECT_UP_TO_TOLERANCE))


# --------------------------------------------------------------------------- #
# 2. Golden verdicts — network pairs (multi-onnx).
# --------------------------------------------------------------------------- #
# (link, out_assert, xf, xg, g_scale, expected)  — f = identity, g = g_scale*X.
_PAIR_GOLDEN = [
    ('iso_true',   '(isomorphic-to f)', '(> Y_f[0,0] Y_g[0,0])', (0.9, 0.1), (0.1, 0.1), 2.0, CexResult.CORRECT),
    ('iso_false',  '(isomorphic-to f)', '(> Y_f[0,0] Y_g[0,0])', (0.1, 0.1), (0.9, 0.1), 2.0, CexResult.SPEC_NOT_VIOLATED),
    ('iso_in_tol', '(isomorphic-to f)', '(> Y_f[0,0] Y_g[0,0])', (0.9, 0.1), (-5e-5, 0.1), 2.0, CexResult.CORRECT_UP_TO_TOLERANCE),
    ('iso_far',    '(isomorphic-to f)', '(> Y_f[0,0] Y_g[0,0])', (0.9, 0.1), (1.5, 0.1), 2.0, CexResult.SPEC_NOT_VIOLATED),
    ('iso_or',     '(isomorphic-to f)', '(or (> Y_f[0,0] Y_g[0,0]) (> Y_f[0,1] 5.0))', (0.9, 0.1), (0.1, 0.1), 2.0, CexResult.CORRECT),
    ('mono_true',  '(equal-to f)',      '(> Y_f[0,0] Y_g[0,0])', (0.9, 0.1), (0.1, 0.1), 1.0, CexResult.CORRECT),
    ('mono_bound', '(equal-to f)',      '(> Y_f[0,0] Y_g[0,0])', (0.5, 0.1), (0.5, 0.1), 1.0, CexResult.SPEC_NOT_VIOLATED),
    # arithmetic in the output atom (exercises Plus/Minus/Multiply):
    ('arith_plus', '(equal-to f)',      '(> Y_f[0,0] (+ Y_g[0,0] 0.1))', (0.9, 0.1), (0.1, 0.1), 1.0, CexResult.CORRECT),
    ('arith_minus','(equal-to f)',      '(> (- Y_f[0,0] Y_g[0,0]) 0.05)', (0.9, 0.1), (0.1, 0.1), 1.0, CexResult.CORRECT),
    ('arith_mul',  '(equal-to f)',      '(> (* Y_f[0,0] 2.0) 1.0)', (0.9, 0.1), (0.1, 0.1), 1.0, CexResult.CORRECT),
]


@pytest.mark.parametrize('name,link,out,xf,xg,scale,expected', _PAIR_GOLDEN,
                         ids=[c[0] for c in _PAIR_GOLDEN])
def test_pair_golden(tmp_path, name, link, out, xf, xg, scale, expected):
    tmp = str(tmp_path)
    pf, pg = pair_nets(tmp, link, scale)
    spec_p = pair_spec(tmp, link, out)
    yf = (xf[0], xf[1])
    yg = (xg[0] * scale, xg[1] * scale)
    ce_p = pair_ce(tmp, xf, yf, xg, yg)
    result, _ = validate_cex_v2([('f', pf), ('g', pg)], spec_p, ce_p)
    assert result == expected


# --------------------------------------------------------------------------- #
# 3. Error dispositions.
# --------------------------------------------------------------------------- #
def test_no_ce(tmp_path):
    tmp = str(tmp_path)
    onnx_p = first_coord_net(tmp)
    spec_p = single_spec(tmp, '(> Y[0,0] 0.5)')
    result, msg = validate_cex_v2(onnx_p, spec_p, os.path.join(tmp, 'missing.ce'))
    assert result == CexResult.NO_CE and 'not found' in msg


def test_spec_parse_error(tmp_path):
    tmp = str(tmp_path)
    onnx_p = first_coord_net(tmp)
    bad_spec = _write(tmp, 'bad.vnnlib', '(this is not valid vnnlib')
    ce_p = single_ce(tmp, 0.9, 0.3, 0.9)
    result, msg = validate_cex_v2(onnx_p, bad_spec, ce_p)
    assert result == CexResult.UNSUPPORTED and 'could not parse' in msg


def test_spec_file_missing(tmp_path):
    tmp = str(tmp_path)
    onnx_p = first_coord_net(tmp)
    ce_p = single_ce(tmp, 0.9, 0.3, 0.9)
    result, _ = validate_cex_v2(onnx_p, os.path.join(tmp, 'nope.vnnlib'), ce_p)
    assert result == CexResult.UNSUPPORTED


# --- malformed counterexample variants -----------------------------------
@pytest.mark.parametrize('ce_text,needle', [
    ('X real [1,2]\n0.9\n0.3\n', 'missing assignment'),                 # truncated (no Y)
    ('not_a_header_line\n', 'invalid assignment header'),               # bad header
    ('Z real [1,2]\n0.9\n0.3\nY real [1,1]\n0.9\n', 'expected variable'),  # wrong name
    ('X real [1,3]\n0\n0\n0\nY real [1,1]\n0\n', 'has shape'),          # shape mismatch
    ('X int8 [1,2]\n0\n0\nY real [1,1]\n0\n', 'has type'),              # type mismatch
    ('X real [1,2]\n0.9\n', 'not enough values'),                       # too few value lines
    ('X real [1,2]\nfoo\n0.3\nY real [1,1]\n0.9\n', 'invalid value'),   # non-numeric
    ('X real [1,2]\n0.9\n0.3\nY real [1,1]\n0.9\nEXTRA\n', 'unexpected content'),  # trailing
])
def test_malformed_ce(tmp_path, ce_text, needle):
    tmp = str(tmp_path)
    onnx_p = first_coord_net(tmp)
    spec_p = single_spec(tmp, '(> Y[0,0] 0.5)')
    ce_p = _write(tmp, 'bad.ce', ce_text)
    result, msg = validate_cex_v2(onnx_p, spec_p, ce_p)
    assert result == CexResult.MALFORMED_CE and needle in msg


# --- resolve-path (UNSUPPORTED) branches ---------------------------------
def test_single_path_with_pair_spec(tmp_path):
    """A single onnx path can't satisfy a 2-implemented-network spec."""
    tmp = str(tmp_path)
    pf = scaled_id_net(tmp, 1.0, 'f.onnx')
    spec_p = pair_spec(tmp, '(isomorphic-to f)', '(> Y_f[0,0] Y_g[0,0])')
    ce_p = pair_ce(tmp, (0.9, 0.1), (0.9, 0.1), (0.1, 0.1), (0.2, 0.2))
    result, msg = validate_cex_v2(pf, spec_p, ce_p)
    assert result == CexResult.UNSUPPORTED and 'exactly one implemented network' in msg


def test_pair_missing_a_path(tmp_path):
    """A named list that omits an implemented (isomorphic) network."""
    tmp = str(tmp_path)
    pf = scaled_id_net(tmp, 1.0, 'f.onnx')
    spec_p = pair_spec(tmp, '(isomorphic-to f)', '(> Y_f[0,0] Y_g[0,0])')
    ce_p = pair_ce(tmp, (0.9, 0.1), (0.9, 0.1), (0.1, 0.1), (0.2, 0.2))
    result, msg = validate_cex_v2([('f', pf)], spec_p, ce_p)
    assert result == CexResult.UNSUPPORTED and 'no ONNX model provided' in msg


def test_equal_to_reuses_single_implemented(tmp_path):
    """A single path IS valid for a monotonic spec (g equal-to f => 1 net)."""
    tmp = str(tmp_path)
    pf = scaled_id_net(tmp, 1.0, 'f.onnx')
    spec_p = pair_spec(tmp, '(equal-to f)', '(> Y_f[0,0] Y_g[0,0])')
    ce_p = pair_ce(tmp, (0.9, 0.1), (0.9, 0.1), (0.1, 0.1), (0.1, 0.1))
    result, _ = validate_cex_v2(pf, spec_p, ce_p)          # single path, resolved for both
    assert result == CexResult.CORRECT


# --- ONNX replay (UNSUPPORTED) branches ----------------------------------
def test_output_shape_mismatch(tmp_path):
    """Spec declares Y[1,2] but the ONNX outputs a single value."""
    tmp = str(tmp_path)
    onnx_p = first_coord_net(tmp)                           # outputs [1,1]
    spec_p = _write(tmp, 'wide.vnnlib',
                    "(vnnlib-version <2.0>)\n"
                    "(declare-network f (declare-input X real [1,2]) (declare-output Y real [1,2]))\n"
                    "(assert (> Y[0,0] 0.5))\n")
    ce_p = _write(tmp, 'wide.ce', "X real [1,2]\n0.9\n0.3\nY real [1,2]\n0.9\n0.0\n")
    result, _ = validate_cex_v2(onnx_p, spec_p, ce_p)
    assert result == CexResult.UNSUPPORTED


def test_output_count_mismatch(tmp_path):
    """Spec declares two outputs but the ONNX has one."""
    tmp = str(tmp_path)
    onnx_p = first_coord_net(tmp)
    spec_p = _write(tmp, 'two_out.vnnlib',
                    "(vnnlib-version <2.0>)\n"
                    "(declare-network f (declare-input X real [1,2]) "
                    "(declare-output Y real [1,1]) (declare-output Z real [1,1]))\n"
                    "(assert (> Y[0,0] 0.5))\n")
    ce_p = _write(tmp, 'two_out.ce',
                  "X real [1,2]\n0.9\n0.3\nY real [1,1]\n0.9\nZ real [1,1]\n0.0\n")
    result, _ = validate_cex_v2(onnx_p, spec_p, ce_p)
    assert result == CexResult.UNSUPPORTED


# --------------------------------------------------------------------------- #
# 4. Direct unit coverage of helpers.
# --------------------------------------------------------------------------- #
def test_parse_assignment_roundtrip(tmp_path):
    import vnnlib
    tmp = str(tmp_path)
    spec_p = single_spec(tmp, '(> Y[0,0] 0.5)')
    query = vnnlib.parse_query_string(open(spec_p).read())
    a = parse_text_assignment("sat\nX real [1,2]\n0.9\n0.3\nY real [1,1]\n0.9\n", query)
    assert np.allclose(a['X'].ravel(), [0.9, 0.3]) and np.allclose(a['Y'].ravel(), [0.9])


def test_validate_cex_v2_ignores_rel_tol(tmp_path):
    tmp = str(tmp_path)
    onnx_p = first_coord_net(tmp)
    spec_p = single_spec(tmp, '(> Y[0,0] 0.5)')
    ce_p = single_ce(tmp, 0.9, 0.3, 0.9)
    r1, _ = validate_cex_v2(onnx_p, spec_p, ce_p, rel_tol=0.0)
    r2, _ = validate_cex_v2(onnx_p, spec_p, ce_p, rel_tol=0.5)
    assert r1 == r2 == CexResult.CORRECT


# --------------------------------------------------------------------------- #
# 5. Additional branch coverage.
# --------------------------------------------------------------------------- #
def _gzip(path):
    import gzip
    with open(path, 'rb') as f:
        data = f.read()
    gz = path + '.gz'
    with gzip.open(gz, 'wb') as f:
        f.write(data)
    return gz


def test_gz_spec_and_onnx(tmp_path):
    """.gz-compressed spec and onnx are read transparently."""
    tmp = str(tmp_path)
    onnx_gz = _gzip(first_coord_net(tmp))
    spec_gz = _gzip(single_spec(tmp, '(> Y[0,0] 0.5)'))
    ce_p = single_ce(tmp, 0.9, 0.3, 0.9)
    result, _ = validate_cex_v2(onnx_gz, spec_gz, ce_p)
    assert result == CexResult.CORRECT


def test_negate_and_and_boolean_atoms(tmp_path):
    """Output atoms exercising Negate and a boolean And (not the box fast path)."""
    tmp = str(tmp_path)
    pf = scaled_id_net(tmp, 1.0, 'f.onnx')
    # (> Y_f[0,0] (- Y_g[0,0]))  and  (and (> Y_f[0,0] 0.0) (> Y_g[0,0] 0.0))
    spec_p = pair_spec(tmp, '(equal-to f)',
                       '(and (> Y_f[0,0] (- Y_g[0,0])) (and (> Y_f[0,0] 0.0) (> Y_g[0,0] 0.0)))')
    ce_p = pair_ce(tmp, (0.9, 0.1), (0.9, 0.1), (0.1, 0.1), (0.1, 0.1))
    result, _ = validate_cex_v2(pf, spec_p, ce_p)
    assert result == CexResult.CORRECT


def test_box_and_bounds_and_strict_and_const_first(tmp_path):
    """Input box written as `(and (>= ..) (<= ..))`, a const-first bound, and
    strict `>`/`<` bounds — all handled by the vectorized box path."""
    tmp = str(tmp_path)
    onnx_p = first_coord_net(tmp)
    spec_p = _write(tmp, 'box.vnnlib',
                    "(vnnlib-version <2.0>)\n"
                    "(declare-network f (declare-input X real [1,2]) (declare-output Y real [1,1]))\n"
                    "(assert (and (>= X[0,0] 0.0) (<= X[0,0] 1.0)))\n"   # And of box atoms
                    "(assert (<= 0.0 X[0,1]))\n"                          # const-first (flip)
                    "(assert (> X[0,1] -1.0))\n"                          # strict GreaterThan box
                    "(assert (< X[0,1] 2.0))\n"                           # strict LessThan box
                    "(assert (> Y[0,0] 0.5))\n")
    ce_p = single_ce(tmp, 0.9, 0.3, 0.9)
    result, _ = validate_cex_v2(onnx_p, spec_p, ce_p)
    assert result == CexResult.CORRECT


def _flat_spec(tmp, name='flat.vnnlib'):
    """Spec declares flat X[2]/Y[2] while the ONNX I/O is [1,2] (reshape by size)."""
    return _write(tmp, name,
                  "(vnnlib-version <2.0>)\n"
                  "(declare-network f (declare-input X real [2]) (declare-output Y real [2]))\n"
                  "(assert (>= X[0] 0.0))(assert (<= X[0] 1.0))\n"
                  "(assert (> Y[0] 0.5))\n")


def test_reshape_by_size(tmp_path):
    """Spec shape [2] vs ONNX shape [1,2]: both input and output reshape by size."""
    tmp = str(tmp_path)
    onnx_p = scaled_id_net(tmp, 1.0, 'id.onnx')            # [1,2] -> [1,2]
    spec_p = _flat_spec(tmp)
    ce_p = _write(tmp, 'flat.ce', "X real [2]\n0.9\n0.3\nY real [2]\n0.9\n0.3\n")
    result, _ = validate_cex_v2(onnx_p, spec_p, ce_p)
    assert result == CexResult.CORRECT


def test_input_reshape_fail_is_unsupported(tmp_path):
    """Spec declares X[3] but the ONNX input is [1,2] (size 3 != 2)."""
    tmp = str(tmp_path)
    onnx_p = scaled_id_net(tmp, 1.0, 'id.onnx')            # input [1,2]
    spec_p = _write(tmp, 'x3.vnnlib',
                    "(vnnlib-version <2.0>)\n"
                    "(declare-network f (declare-input X real [3]) (declare-output Y real [2]))\n"
                    "(assert (> Y[0] 0.5))\n")
    ce_p = _write(tmp, 'x3.ce', "X real [3]\n0.9\n0.3\n0.1\nY real [2]\n0.9\n0.3\n")
    result, msg = validate_cex_v2(onnx_p, spec_p, ce_p)
    assert result == CexResult.UNSUPPORTED and 'cannot reshape' in msg


def _double_id_net(tmp, name='dbl.onnx'):
    """Identity [1,2] -> [1,2] with DOUBLE (float64) element type."""
    inp = helper.make_tensor_value_info('X', TensorProto.DOUBLE, [1, 2])
    out = helper.make_tensor_value_info('Y', TensorProto.DOUBLE, [1, 2])
    node = helper.make_node('Identity', ['X'], ['Y'])
    graph = helper.make_graph([node], 'm', [inp], [out])
    model = helper.make_model(graph, opset_imports=[helper.make_opsetid('', 13)])
    model.ir_version = 7
    return _save_onnx(model, tmp, name)


def test_element_type_mismatch_is_unsupported(tmp_path):
    """Spec declares X as f32 but the ONNX input is double."""
    tmp = str(tmp_path)
    onnx_p = _double_id_net(tmp)
    spec_p = _write(tmp, 'typed.vnnlib',
                    "(vnnlib-version <2.0>)\n"
                    "(declare-network f (declare-input X float32 [1,2]) (declare-output Y float32 [1,2]))\n"
                    "(assert (> Y[0,0] 0.5))\n")
    ce_p = _write(tmp, 'typed.ce', "X float32 [1,2]\n0.9\n0.3\nY float32 [1,2]\n0.9\n0.3\n")
    result, msg = validate_cex_v2(onnx_p, spec_p, ce_p)
    assert result == CexResult.UNSUPPORTED and 'type' in msg


def test_parse_scalar_bool_and_int():
    """_parse_scalar's boolean and integer branches (float is the common path)."""
    from vibecheck.cex_check_v2 import _parse_scalar
    assert _parse_scalar('true', np.bool_) is True
    assert _parse_scalar('1', np.bool_) is True
    assert _parse_scalar('false', np.bool_) is False
    assert _parse_scalar('42', np.int32) == 42
    with pytest.raises(ValueError):
        _parse_scalar('maybe', np.bool_)


def test_unsupported_ast_nodes_raise():
    """The dispatch terminators: an unrecognized AST node is never silently
    skipped (mirrors the op-dispatch soundness rule)."""
    from vibecheck.cex_check_v2 import _eval_arithmetic, _eval_boolean, _Unsupported

    class Weird:                           # an arithmetic node type not handled
        pass

    class Float:                           # mimics the vnnlib Float leaf (has .value)
        def __init__(self, v):
            self.value = v

    class WeirdCmp:                        # a comparison kind not handled (valid lhs/rhs)
        lhs = Float(1.0)
        rhs = Float(0.0)

    with pytest.raises(_Unsupported):
        _eval_arithmetic(Weird(), {})
    with pytest.raises(_Unsupported):
        _eval_boolean(WeirdCmp(), {}, 0.0)


def test_equal_and_notequal_input_pins(tmp_path):
    """`(== ..)` / `(!= ..)` atoms — monotonic specs pin inputs with `==`."""
    tmp = str(tmp_path)
    onnx_p = first_coord_net(tmp)
    spec_p = _write(tmp, 'pins.vnnlib',
                    "(vnnlib-version <2.0>)\n"
                    "(declare-network f (declare-input X real [1,2]) (declare-output Y real [1,1]))\n"
                    "(assert (== X[0,0] 0.5))\n"        # Equal input pin
                    "(assert (!= X[0,1] 0.0))\n"        # NotEqual
                    "(assert (> Y[0,0] 0.3))\n")
    ce_p = single_ce(tmp, 0.5, 0.7, 0.5)               # Y = X[0,0] = 0.5 > 0.3
    result, _ = validate_cex_v2(onnx_p, spec_p, ce_p)
    assert result == CexResult.CORRECT
    # A witness that breaks the `==` pin (X[0,0]=0.6) is not accepted.
    ce_bad = single_ce(tmp, 0.6, 0.7, 0.6, name='bad.ce')
    result2, _ = validate_cex_v2(onnx_p, spec_p, ce_bad)
    assert result2 == CexResult.SPEC_NOT_VIOLATED


def test_literal_arithmetic_node():
    """Literal leaf handling in _eval_arithmetic/_const (the vnnlib grammar
    includes it; the pinned parser emits Float, so exercise it directly)."""
    from vibecheck.cex_check_v2 import _eval_arithmetic, _const

    class Literal:                         # type name drives the dispatch
        lexeme = "1.5"

    assert _eval_arithmetic(Literal(), {}) == 1.5
    assert _const(Literal()) == 1.5


def test_unsupported_onnx_input_type(tmp_path):
    """An ONNX input whose element type vibecheck has no numpy mapping for."""
    tmp = str(tmp_path)
    inp = helper.make_tensor_value_info('X', TensorProto.BFLOAT16, [1, 2])
    out = helper.make_tensor_value_info('Y', TensorProto.BFLOAT16, [1, 2])
    graph = helper.make_graph([helper.make_node('Identity', ['X'], ['Y'])], 'm', [inp], [out])
    model = helper.make_model(graph, opset_imports=[helper.make_opsetid('', 13)])
    model.ir_version = 7
    onnx_p = _save_onnx(model, tmp, 'bf16.onnx')
    spec_p = _write(tmp, 'bf16.vnnlib',
                    "(vnnlib-version <2.0>)\n"
                    "(declare-network f (declare-input X real [1,2]) (declare-output Y real [1,2]))\n"
                    "(assert (> Y[0,0] 0.5))\n")
    ce_p = _write(tmp, 'bf16.ce', "X real [1,2]\n0.9\n0.3\nY real [1,2]\n0.9\n0.3\n")
    result, msg = validate_cex_v2(onnx_p, spec_p, ce_p)
    assert result == CexResult.UNSUPPORTED and 'input type' in msg
